### ISSUE TITLE
oop의 4가지 특성에 대해 설명해보세요

### ISSUE THREAD

**Issue by minje0204** [Java-3-0/CS-study#1]
# 질문자
전선영 @sally2596

**Comment by minje0204** [comment]
**APIE**
Encapsulation 캡슐화

객체 기능구현을 내부에 숨김 → 정보은닉

적절한 캡술화 → 응집도 👍

→구현내용을 내부에 숨겨서, 응집도를 높이는 것 (고객 <지갑>신문 배달부 예시)

Inheritance 상속

상위클래스의 코드를 이를 상속받는 하위클래스가 사용할 수 있게하여 코드재사용성을 높혀준다. 계층관계를 쉽게 나타낼 수 있다.

Abstraction 추상화

복잡한 객체의 특성을 단순화, 공통된 특성을 추출하는 것

→최소한의 정보로 도메인 데이터를 추출하는것 (지하철 노선도, 인터페이스 타입, 추상화 타입)

Polymorphism 다형성

→한 가지 역할이 상황에 따라 각기 다른 행동을 한다 (주방장 기침 → 부주방장 요리사 눈치)

~~다형성을 활용하면 관심사의 분리, 확장에 열려있는 코드를 짤 수 있고 이는 유지보수를 보다 편하게 해준다.(처음 답변)~~

**Comment by sally2596** [comment]
oop의 4가지 특성으로는 추상화, 캡슐화, 상속성, 다형성이 있습니다.

추상화는 객체의 대표적인 특성을 추출해내어 수퍼클래스를 생성하는 것입니다.

캡슐화는 객체의 속성과 메서드를 접근제한자를 통해 은닉하는 것입니다.

상속성은 상위 클래스의 내용을 하위 클래스가 받아서 사용, 추가, 확장하는 것입니다.

다형성은 메서드나 클래스가 다양한 방법으로 동작하는 것입니다.
