### ISSUE TITLE
정규화와 반정규화를 차이점을 들어 설명하시오. 반정규화를 하는 이유는 무엇입니까?

### ISSUE THREAD

**Issue by sally2596** [Java-3-0/CS-study#11]

**Comment by Emmental1230** [comment]
정규화
- 정규화는 데이터의 일관성, 최소한의 데이터 중복, 최소한의 데이터 유연성을 위해 데이터를 분해하는 과정
반정규화
- 성능을 향상시키기 위해 정규화된 데이터 모델에서 중복, 통합, 분리 등을 수행하는 모든 과정

반정규화를 수행하는 이유
- 정규화에 충실하여 종속성, 활용성은 향상 되었지만 수행속도가 느려진 경우
- 다량의 범위를 자주 처리해야하는 경우
- 특정 범위의 데이터만 자주 처리하는 경우
