### ISSUE TITLE
DNS 리졸버는 왜 TCP가 아닌 UDP를 사용하는지 설명하시오.

### ISSUE THREAD

**Issue by minje0204** [Java-3-0/CS-study#2]
## DNS 리졸버는 왜 TCP가 아닌 UDP를 사용하는지 설명하시오.

> 클라이언트 단에서 서버에 요청을 보낼때 우리는 ip주소를 직접 사용하지 않고 domain name을 사용한다. 여기서 리졸버는 네임서버(Nameserver)로 원하는 호스트(Host)에 대한 쿼리(Query)를 보내고 네임서버로부터 받은 응답(매핑되는 ip주소)을 해석하고 정보를 요구한 클라이언트에 정보를 전달한다. 
> 
> **인터넷 상의(외부) 도메인의 이름풀이를 제공하는 것이 주 목적이다.**

### DNS 리졸버는 TCP가 아닌 UDP를 사용한다 하는데 그 이유가 무엇일까??
---
### 질문자
조민제 @minje0204

**Comment by Emmental1230** [comment]
1. 연결 설정이 없다.
2. 연결상태가 없다.
3. 작은 패킷 헤더 오버헤드
4. 정교한 제어

**Comment by minje0204** [comment]
**1)** UDP is much faster. TCP is slow as it requires a 3-way handshake. The load on DNS servers is also an important factor. DNS servers (since they use UDP) don’t have to keep connections.

훨씬 빠름 + dns서버는 연결을 지속할 필요가없다.

**2)** DNS requests are generally very small and fit well within UDP segments.

dns 요청자체 메시지 크기가메우 작아서 udp 세그먼트 안에 모두 들어갈 수 있다.

**3)** UDP is not reliable, but reliability can be added to the application layer. An application can use UDP and can be reliable by using a timeout and resend at the application layer.

udp는 신뢰성 보장 안하지만 어플리케이션 계층에서 이를 추가할수 있따. 다시말하면 어플리케이션 레이어단에서 timeout이 일어나면 재전송을 요청하게 함으로써 이게 가능하다.
