### ISSUE TITLE
인덱스를 만들 칼럼에 카디널리티가 높을수록 유리할까 낮을 수록 유리할까? 그리고 그 이유는

### ISSUE THREAD

**Issue by minje0204** [Java-3-0/CS-study#9]
인덱스를 만들 칼럼에 카디널리티가 높을수록 유리할까 낮을 수록 유리할까? 그리고 그 이유는

**Comment by minje0204** [comment]
✔️ 카디널리티가 높을 수록 인덱스 설정에 좋은 컬럼입니다.
= 한 컬럼이 갖고 있는 값의 중복 정도가 낮을 수록 좋습니다.

컬럼에 사용되는 값의 다양성 정도, 즉 중복 수치를 나타내는 지표입니다.
후보 컬럼에 따라 상대적으로 중복 정도가 낮다, 혹은 높다로 표현됩니다.

https://yurimkoo.github.io/db/2020/03/14/db-index.html

**Comment by Emmental1230** [comment]
카디널리티는 컬럼에 사용되는 값의 다양성 정도, 즉 중복 수치를 나타내는 지표이다. 후보 컬럼에 따라 상대적으로 중복 정도가 낮다, 혹은 높다로 표현한다.

예를 들어, 10개의 행을 갖는 '학생' 테이블에 학번과 이름 컬럼이 있다고 하자. 학번은 학생마다 고유하게 부여받는 값이므로 10개의 값 모두가 고유한 값이다. 이름은 동명이인이 있을 수 있으니 1 ~ 10 의 카디널리티 값을 갖는다. 즉, 상대적으로 학번이 이름에 비해 카디널리티 값이 높으므로 인덱스로 설정하기에 알맞다.

카디널리티가 높을수록 인덱스 설정에 좋은 컬럼이다.
(= 한 칼럼이 갖고 있는 값의 중복 정도가 낮을수록 좋다.)
